-- MySQL Script generated by MySQL Workbench
-- Sun Jul  8 13:49:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema papergenerate
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `papergenerate` ;

-- -----------------------------------------------------
-- Schema papergenerate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `papergenerate` DEFAULT CHARACTER SET utf8 ;
USE `papergenerate` ;

-- -----------------------------------------------------
-- Table `papergenerate`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papergenerate`.`user` ;

CREATE TABLE IF NOT EXISTS `papergenerate`.`user` (
  `userid` INT(10) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(93) NOT NULL,
  `course` INT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `papergenerate`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papergenerate`.`question` ;

CREATE TABLE IF NOT EXISTS `papergenerate`.`question` (
  `qid` INT(10) NOT NULL AUTO_INCREMENT,
  `question` TEXT NOT NULL,
  `type` INT NULL DEFAULT 0,
  `delornot` TINYINT NULL DEFAULT 0,
  `level` INT NULL DEFAULT 0,
  `course` INT NULL,
  PRIMARY KEY (`qid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `papergenerate`.`choices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papergenerate`.`choices` ;

CREATE TABLE IF NOT EXISTS `papergenerate`.`choices` (
  `question_qid` INT(10) NOT NULL,
  `cid` INT(10) NOT NULL AUTO_INCREMENT,
  `choice` TEXT NULL,
  `torf` TINYINT NULL,
  PRIMARY KEY (`cid`),
  INDEX `fk_choices_question1_idx` (`question_qid` ASC),
  CONSTRAINT `fk_choices_question1`
    FOREIGN KEY (`question_qid`)
    REFERENCES `papergenerate`.`question` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `papergenerate`.`qanswer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `papergenerate`.`qanswer` ;

CREATE TABLE IF NOT EXISTS `papergenerate`.`qanswer` (
  `question_qid` INT(10) NOT NULL,
  `qanswer` TEXT NULL,
  INDEX `fk_qanswer_question1_idx` (`question_qid` ASC),
  CONSTRAINT `fk_qanswer_question1`
    FOREIGN KEY (`question_qid`)
    REFERENCES `papergenerate`.`question` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
